language: objective-c
before_install:
  - export LANG="en_US.UTF-8"
#  - gem update --system
  - brew update
  - brew upgrade xctool;true
  - brew install cmake
  - gem install cocoapods
before_script:
  - mkdir -p ../viewer/resources
  - touch ../viewer/resources/report_blacklist.json
  - touch ../viewer/resources/index.html
xcode_workspace: KCTViewer.xcworkspace
xcode_scheme: KCTViewer

