language: objective-c
before_install:
  - export LANG="en_US.UTF-8"
  - gem update --system
  - brew update
  - gem install cocoapods
install:
  - brew upgrade xctool
  - pod install
xcode_workspace: KCTViewer.xcworkspace
xcode_scheme: KCTViewer
xcode_sdk: macosx10.9
